apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-local-dns
  namespace: pihole
data:
  # All .home names resolve to the Ingress-NGINX MetalLB IP
  homelab.conf: |
    address=/ai.home/192.168.0.201
    address=/grafana.home/192.168.0.201
    address=/prometheus.home/192.168.0.201
    address=/alertmanager.home/192.168.0.201
    address=/pihole.home/192.168.0.201
    address=/searxng.home/192.168.0.201
    address=/argocd.home/192.168.0.201
    address=/ollama.home/192.168.0.201
    address=/status.home/192.168.0.201
