apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab-twin
  namespace: lab-twin
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - labtwin.home
        - twin.home
      secretName: labtwin-tls
  rules:
    - host: labtwin.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lab-twin
                port:
                  number: 80
    - host: twin.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lab-twin
                port:
                  number: 80
