apiVersion: v1
kind: Service
metadata:
  name: lab-twin
  namespace: lab-twin
  labels:
    app: lab-twin
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
  selector:
    app: lab-twin
