apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: learning
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/raghavendrak89/home_lab.git
    targetRevision: main
    path: kubernetes/apps/learning
  destination:
    server: https://kubernetes.default.svc
    namespace: learning
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
